# Generated by Django 2.0 on 2017-12-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('女', 'famale'), ('男', 'male')], max_length=1)),
            ],
        ),
    ]
