# Generated by Django 2.0 on 2018-01-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BRS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookRank',
            fields=[
                ('bookid', models.AutoField(db_column='BookId', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('href', models.CharField(blank=True, max_length=80, null=True)),
                ('keyword1', models.CharField(blank=True, db_column='KeyWord1', max_length=2, null=True)),
                ('keyword2', models.CharField(blank=True, db_column='KeyWord2', max_length=2, null=True)),
                ('keyword3', models.CharField(blank=True, db_column='KeyWord3', max_length=2, null=True)),
                ('keyword4', models.CharField(blank=True, db_column='KeyWord4', max_length=2, null=True)),
                ('keyword5', models.CharField(blank=True, db_column='KeyWord5', max_length=2, null=True)),
                ('keyword6', models.CharField(blank=True, db_column='KeyWord6', max_length=2, null=True)),
                ('keyword7', models.CharField(blank=True, db_column='KeyWord7', max_length=2, null=True)),
                ('keyword8', models.CharField(blank=True, db_column='KeyWord8', max_length=2, null=True)),
                ('keyword9', models.CharField(blank=True, db_column='KeyWord9', max_length=2, null=True)),
                ('keyword10', models.CharField(blank=True, db_column='KeyWord10', max_length=2, null=True)),
                ('keyword11', models.CharField(blank=True, db_column='KeyWord11', max_length=2, null=True)),
                ('keyword12', models.CharField(blank=True, db_column='KeyWord12', max_length=2, null=True)),
                ('keyword13', models.CharField(blank=True, db_column='KeyWord13', max_length=2, null=True)),
                ('keyword14', models.CharField(blank=True, db_column='KeyWord14', max_length=2, null=True)),
                ('keyword15', models.CharField(blank=True, db_column='KeyWord15', max_length=2, null=True)),
                ('keyword16', models.CharField(blank=True, db_column='KeyWord16', max_length=2, null=True)),
                ('keyword17', models.CharField(blank=True, db_column='KeyWord17', max_length=2, null=True)),
                ('keyword18', models.CharField(blank=True, db_column='KeyWord18', max_length=2, null=True)),
                ('keyword19', models.CharField(blank=True, db_column='KeyWord19', max_length=2, null=True)),
                ('keyword20', models.CharField(blank=True, db_column='KeyWord20', max_length=2, null=True)),
                ('keyword21', models.CharField(blank=True, db_column='KeyWord21', max_length=2, null=True)),
                ('keyword22', models.CharField(blank=True, db_column='KeyWord22', max_length=2, null=True)),
                ('keyword23', models.CharField(blank=True, db_column='KeyWord23', max_length=2, null=True)),
                ('keyword24', models.CharField(blank=True, db_column='KeyWord24', max_length=2, null=True)),
                ('keyword25', models.CharField(blank=True, db_column='KeyWord25', max_length=2, null=True)),
                ('keyword26', models.CharField(blank=True, db_column='KeyWord26', max_length=2, null=True)),
                ('keyword27', models.CharField(blank=True, db_column='KeyWord27', max_length=2, null=True)),
                ('keyword28', models.CharField(blank=True, db_column='KeyWord28', max_length=2, null=True)),
                ('keyword29', models.CharField(blank=True, db_column='KeyWord29', max_length=2, null=True)),
                ('keyword30', models.CharField(blank=True, db_column='KeyWord30', max_length=2, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('writer', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'book_rank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Newbook',
            fields=[
                ('newbookid', models.AutoField(db_column='NewBookId', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('href', models.CharField(blank=True, max_length=80, null=True)),
                ('keyword1', models.CharField(blank=True, db_column='KeyWord1', max_length=2, null=True)),
                ('keyword2', models.CharField(blank=True, db_column='KeyWord2', max_length=2, null=True)),
                ('keyword3', models.CharField(blank=True, db_column='KeyWord3', max_length=2, null=True)),
                ('keyword4', models.CharField(blank=True, db_column='KeyWord4', max_length=2, null=True)),
                ('keyword5', models.CharField(blank=True, db_column='KeyWord5', max_length=2, null=True)),
                ('keyword6', models.CharField(blank=True, db_column='KeyWord6', max_length=2, null=True)),
                ('keyword7', models.CharField(blank=True, db_column='KeyWord7', max_length=2, null=True)),
                ('keyword8', models.CharField(blank=True, db_column='KeyWord8', max_length=2, null=True)),
                ('keyword9', models.CharField(blank=True, db_column='KeyWord9', max_length=2, null=True)),
                ('keyword10', models.CharField(blank=True, db_column='KeyWord10', max_length=2, null=True)),
                ('keyword11', models.CharField(blank=True, db_column='KeyWord11', max_length=2, null=True)),
                ('keyword12', models.CharField(blank=True, db_column='KeyWord12', max_length=2, null=True)),
                ('keyword13', models.CharField(blank=True, db_column='KeyWord13', max_length=2, null=True)),
                ('keyword14', models.CharField(blank=True, db_column='KeyWord14', max_length=2, null=True)),
                ('keyword15', models.CharField(blank=True, db_column='KeyWord15', max_length=2, null=True)),
                ('keyword16', models.CharField(blank=True, db_column='KeyWord16', max_length=2, null=True)),
                ('keyword17', models.CharField(blank=True, db_column='KeyWord17', max_length=2, null=True)),
                ('keyword18', models.CharField(blank=True, db_column='KeyWord18', max_length=2, null=True)),
                ('keyword19', models.CharField(blank=True, db_column='KeyWord19', max_length=2, null=True)),
                ('keyword20', models.CharField(blank=True, db_column='KeyWord20', max_length=2, null=True)),
                ('keyword21', models.CharField(blank=True, db_column='KeyWord21', max_length=2, null=True)),
                ('keyword22', models.CharField(blank=True, db_column='KeyWord22', max_length=2, null=True)),
                ('keyword23', models.CharField(blank=True, db_column='KeyWord23', max_length=2, null=True)),
                ('keyword24', models.CharField(blank=True, db_column='KeyWord24', max_length=2, null=True)),
                ('keyword25', models.CharField(blank=True, db_column='KeyWord25', max_length=2, null=True)),
                ('keyword26', models.CharField(blank=True, db_column='KeyWord26', max_length=2, null=True)),
                ('keyword27', models.CharField(blank=True, db_column='KeyWord27', max_length=2, null=True)),
                ('keyword28', models.CharField(blank=True, db_column='KeyWord28', max_length=2, null=True)),
                ('keyword29', models.CharField(blank=True, db_column='KeyWord29', max_length=2, null=True)),
                ('keyword30', models.CharField(blank=True, db_column='KeyWord30', max_length=2, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'newbook',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sortkeywords',
            fields=[
                ('skwid', models.IntegerField(primary_key=True, serialize=False)),
                ('skw', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sortkeywords',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': False},
        ),
    ]
