# Generated by Django 2.0 on 2018-01-09 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BRS', '0002_auto_20180109_1132'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='brs_userinfo',
        ),
    ]
