# Generated by Django 2.0 on 2018-01-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BRS', '0003_auto_20180109_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrsPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=84)),
            ],
            options={
                'db_table': 'brs_person',
                'managed': False,
            },
        ),
    ]
